apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: calibre-web
version: 2.0.0
upstream_version: 4.3.1
appVersion: "auto"
description: Calibre-Web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/calibre-web
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
keywords:
  - calibre-web
  - calibre
  - ebook
sources:
  - https://github.com/truecharts/charts/tree/master/charts/calibre-web
  - https://github.com/k8s-at-home/charts/tree/master/charts/calibre-web
  - https://hub.docker.com/r/linuxserver/calibre-web/
  - https://github.com/janeczku/calibre-web
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 2.0.0
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
