
# Default values for Organizr.

image:
  repository: organizr/organizr
  pullPolicy: Always
  tag: latest

strategy:
  type: Recreate

services:
  main:
    port:
      port: 80

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

## TrueCharts Config


appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
