apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: emby
version: 2.0.0
# upstream_version:
appVersion:  "auto"
description: Emby Server is a home media server
type: application
deprecated: false
home: https://github.com/djs52/charts/tree/master/charts/emby
icon_url: https://raw.githubusercontent.com/djs52/charts/master/charts/emby/icon.png?raw=true
keywords:
  - jellyfin
  - plex
  - emby
sources:
  - https://github.com/truecharts/charts/tree/master/charts/emby
  - https://hub.docker.com/r/linuxserver/emby
  - https://github.com/linuxserver/docker-emby.git
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 2.0.0
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Dan Sheridan
    email: dan.sheridan@postman.org.uk
    url: truecharts.org
# annotations:
