# Default values for Tautulli.

image:
  repository: tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.6.6

strategy:
  type: Recreate

startAsRoot: true

services:
  main:
    port:
      port: 8181

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: "/config"

## TrueCharts Config

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
