apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: collabora-online
version: 2.0.0
# upstream_version:
appVersion: "auto"
description: Collabora Online Development Edition – an awesome, Online Office suite image suitable for home use.
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/collabora-online
icon: https://avatars.githubusercontent.com/u/22418908?s=200&v=4
keywords:
  - collabora-online
sources:
  - https://github.com/truecharts/apps/tree/master/stable/collabora-online
  - https://github.com/k8s-at-home/charts/tree/master/charts/collabora-online
  - https://hub.docker.com/r/collabora/code
  - https://www.collaboraoffice.com/code/docker/
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: stavros-k
    email: stavros-k@users.noreply.github.com
    url: truecharts.org
# annotations:
