# Default values for Sabnzbd.

image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: 5.3

strategy:
  type: Recreate

services:
  main:
    port:
      port: 8080

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/var/lib/pgadmin"
