# Default values for grocy.

image:
  repository: linuxserver/grocy
  tag: version-v2.7.1
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

services:
  main:
    port:
      port: 80

env: {}
  # TZ:
  # PUID:
  # PGID:

persistence:
  config:
    enabled: false
    emptyDir: false




appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
