image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

services:
  main:
    port:
      port: 8080
  extra-tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: tcp-test
      protocol: TCP
      targetPort: 51414
  extra-udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51414
      name: udp-test
      protocol: UDP
      targetPort: 51414

ingress:
  enabled: true

persistence:
  config:
    enabled: true
    emptyDir: true
    mountPath: /www/assets

addons:
  codeserver:
    enabled: true
    workingDir: "/www/assets"
    ingress:
      enabled: true
    volumeMounts:
    - name: config
      mountPath: /www/assets

fixMountPermissions: false
appVolumeMounts:
  data:
    enabled: true
    emptyDir: true
    datasetName: "data"
    mountPath: "/data"
    hostPathEnabled: false
    hostPath: ""
  test:
    enabled: true
    emptyDir: false
    datasetName: "test"
    mountPath: "/test"
    hostPathEnabled: true
    hostPath: "/tmp"

appExtraVolumeMounts:
  - name: "extratest1"
    enabled: true
    emptyDir: true
    datasetName: "extratest1"
    mountPath: "/extratest1"
    hostPathEnabled: false
    hostPath: ""
  - name: "extratest2"
    enabled: true
    emptyDir: false
    datasetName: "extratest2"
    mountPath: "/extratest2"
    hostPathEnabled: true
    hostPath: "/tmp"
