# Default values for InfluxDB

image:
  repository: influxdb
  pullPolicy: IfNotPresent
  tag: 2.0.4

strategy:
  type: Recreate

envTpl:
  DOCKER_INFLUXDB_INIT_MODE: "setup"

services:
  main:
    port:
      port: 8086
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 2003
      protocol: TCP
      targetPort: 2003

# Volumes

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/etc/influxdb2"
  data:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/var/lib/influxdb2"

envTpl:
  DOCKER_INFLUXDB_INIT_USERNAME: "{{ .Values.username }}"
  DOCKER_INFLUXDB_INIT_PASSWORD: "{{ .Values.password }}"
  DOCKER_INFLUXDB_INIT_ORG: "{{ .Values.org }}"
  DOCKER_INFLUXDB_INIT_BUCKET: "{{ .Values.bucket }}"
  DOCKER_INFLUXDB_INIT_RETENTION: "{{ .Values.retention }}"
  #DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ .Values.admintoken }}"