apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: tvheadend
<<<<<<< HEAD:charts/tvheadend/1.6.4/Chart.yaml
version: 1.6.4
=======
version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/tvheadend/2.0.0/Chart.yaml
upstream_version: 1.1.2
appVersion: "latest"
description: TVheadend - a TV streaming server and digital video recorder
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/tvheadend
icon: https://avatars.githubusercontent.com/u/1908588?s=200&v=4
keywords:
  - tvheadend
  - tv
  - streaming
  - dvb
sources:
  - https://github.com/truecharts/charts/tree/master/charts/tvheadend
  - https://github.com/k8s-at-home/charts/tree/master/charts/tvheadend
  - https://github.com/tvheadend/tvheadend
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
<<<<<<< HEAD:charts/tvheadend/1.6.4/Chart.yaml
    version: 1.6.7
=======
    version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/tvheadend/2.0.0/Chart.yaml
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@$truecharts.org
    url: truecharts.org
# annotations:
