{{- if .Values.certmanager.wildcardDomain -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcardcert
  annotations:
   # hooks are defined here
   "helm.sh/hook": post-install,post-upgrade
   "helm.sh/hook-weight": "10"
   "helm.sh/hook-delete-policy": before-hook-creation
   reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
spec:
  commonName: {{ .Values.certmanager.wildcardDomain }}
  secretName: wildcardcert
  dnsNames:
  - {{ .Values.certmanager.wildcardDomain }}
  - '*.{{ .Values.certmanager.wildcardDomain }}'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
