apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: emby
version: 2.0.0
# upstream_version:
appVersion:  "auto"
description: Emby Server is a home media server
type: application
deprecated: false
home: https://github.com/truecharts/apps/raw/master/charts/emby
icon: https://github.com/truecharts/apps/raw/master/charts/emby/icon.png
keywords:
  - jellyfin
  - plex
  - emby
sources:
  - https://github.com/truecharts/apps/tree/master/stable/emby
  - https://hub.docker.com/r/linuxserver/emby
  - https://github.com/linuxserver/docker-emby.git
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Dan Sheridan
    email: dan.sheridan@postman.org.uk
    url: truecharts.org
# annotations:
