# Default values for Jackett.

image:
  repository: linuxserver/transmission
  pullPolicy: IfNotPresent
  tag: version-3.00-r2

strategy:
  type: Recreate

services:
  main:
    port:
      port: 9091
#  tcp:
#    enabled: true
#    type: ClusterIP
#    port:
#      port: 51413
#      protocol: TCP
#      targetPort: 51413
#      nodePort: 51413
#  udp:
#    enabled: true
#    type: ClusterIP
#    port:
#      port: 51413
#      protocol: UDP
#      targetPort: 51413
#      nodePort: 51413

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

## TrueCharts Values




#appVolumeMounts:
#  config:
#    enabled: true
#    emptyDir: false
#    datasetName: "config"
#  downloads:
#    enabled: true
#    emptyDir: false
#    datasetName: "downloads"
