apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: common-test
version: 2.0.0
# upstream_version:
appVersion: none
description: Helper chart to test different use cases of the common library
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/library/common-test
icon: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
keywords:
  - common-test
  - truecharts
  - common
  - test
sources:
  - https://github.com/truecharts/apps/tree/master/library/common-test
dependencies:
  - name: common
    repository: file://../common
    version: latest
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
