apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: common-test
version: 2.0.0
# upstream_version:
# appVersion:
description: Helper chart to test different use cases of the common library
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/library/common-test
# icon:
keywords:
  - common-test
  - truecharts
  - common
  - test
sources:
  - https://github.com/truecharts/charts/tree/master/library/common-test
dependencies:
  - name: common
    repository: file://../common
    version: n/a
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
