image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

services:
  main:
    port:
      port: 8080
  test2-tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 8081
      name: tcp-test
      protocol: TCP
      targetPort: 8081
  test2-udp:
    enabled: true
    type: ClusterIP
    port:
      port: 8082
      name: udp-test
      protocol: UDP
      targetPort: 8082

additionalServices:
  - name: test3-tcp
    enabled: true
    type: ClusterIP
    port:
      port: 8083
      name: tcp-test
      protocol: TCP
      targetPort: 8083
  - name: test4-dp
    enabled: true
    type: ClusterIP
    port:
      port: 8084
      name: udp-test
      protocol: UDP
      targetPort: 8084

ingress:
  enabled: true

# these values and names are set specifically with the unittests in mind.
fixMountPermissions: false
appVolumeMounts:
  test1:
    enabled: true
    emptyDir: true
    datasetName: "test1"
    mountPath: "/test1"
    hostPathEnabled: false
    hostPath: ""
  test2:
    enabled: true
    emptyDir: false
    datasetName: "test2"
    mountPath: "/test2"
    hostPathEnabled: true
    hostPath: "/tmp"

# these values and names are set specifically with the unittests in mind.
additionalAppVolumeMounts:
  - name: "test3"
    enabled: true
    emptyDir: true
    datasetName: "test3"
    mountPath: "/test3"
    hostPathEnabled: false
    hostPath: ""
  - name: "test4"
    enabled: true
    emptyDir: false
    datasetName: "test4"
    mountPath: "/test4"
    hostPathEnabled: true
    hostPath: "/tmp"
