apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: handbrake
version: 2.0.0
# upstream_version:
appVersion: "auto"
description: HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs.
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/handbrake
icon: https://handbrake.fr/img/logo.png
keywords:
  - handbrake
  - encode
  - media
sources:
  - https://github.com/truecharts/apps/tree/master/stable/handbrake
  - https://github.com/jlesage/docker-handbrake
  - https://hub.docker.com/r/jlesage/handbrake/
  - https://handbrake.fr/
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: stavros-k
    email: stavros-k@users.noreply.github.com
    url: truecharts.org
# annotations:
