# Default values for Radarr.

image:
  repository: ghcr.io/k8s-at-home/radarr
  pullPolicy: IfNotPresent
  tag: v3.0.2.4552

strategy:
  type: Recreate

services:
  main:
    port:
      port: 7878

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: false
    emptyDir: false

  media:
    enabled: false
    emptyDir: false
    mountPath: /media
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""

## TrueCharts Config

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
  media:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/media"
  downloads:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/downloads"
