apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: traefik
version: 2.0.0
upstream_version: 9.15.2
appVersion: "auto"
description: A Traefik based Reverse Proxy and Certificate Manager
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/traefik
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
  - traefik
  - ingress
sources:
  - https://github.com/truecharts/apps/tree/master/stable/traefik
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
  - https://traefik.io/
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Ornias1993
    email: kjeld@schouten-lebbing.nl
    url: truecharts.org
# annotations:
