apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: nzbget
version: 2.0.0
upstream_version: 7.3.1
appVersion: "auto"
description: NZBGet is a Usenet downloader client
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/nzbget
icon: https://avatars1.githubusercontent.com/u/3368377?s=400&v=4
keywords:
  - nzbget
  - usenet
sources:
  - https://github.com/truecharts/apps/tree/master/stable/nzbget
  - https://github.com/k8s-at-home/charts/tree/master/charts/nzbget
  - https://hub.docker.com/r/linuxserver/nzbget/
  - https://nzbget.net/
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
