# Default values for nzbget.

image:
  repository: ghcr.io/truecharts/nzbget
  pullPolicy: IfNotPresent
  tag: v21.0

strategy:
  type: Recreate

services:
  main:
    port:
      port: 6789

persistence:
  config:
    enabled: false
    emptyDir: false

  media:
    enabled: false
    emptyDir: false
    mountPath: /media
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""

  downloads:
    enabled: false
    emptyDir: false
    mountPath: /downloads
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
  media:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/media"
  downloads:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/downloads"
