apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: esphome
version: 2.0.0
upstream_version: 4.3.1
appVersion: "auto"
description: ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/esphome
icon: https://esphome.io/_images/logo.svg
keywords:
  - esphome
sources:
  - https://github.com/truecharts/charts/tree/master/charts/esphome
  - https://github.com/k8s-at-home/charts/tree/master/charts/esphome
  - https://github.com/esphome/esphome
  - https://hub.docker.com/u/esphome
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 2.0.0
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Troy Prelog
    email: 35702532+tprelog@users.noreply.github.com
    url: truecharts.org
# annotations:
