apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: gaps
<<<<<<< HEAD:charts/gaps/1.6.4/Chart.yaml
version: 1.6.4
=======
version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/gaps/2.0.0/Chart.yaml
upstream_version: 1.1.1
appVersion: "auto"
description: Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection.
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/gaps
icon: https://raw.githubusercontent.com/JasonHHouse/gaps/master/images/Final-Black.png
keywords:
  - gaps
  - plex
  - plex-media-server
sources:
  - https://github.com/truecharts/charts/tree/master/charts/gaps
  - https://github.com/k8s-at-home/charts/tree/master/charts/gaps
  - https://github.com/JasonHHouse/gaps
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
<<<<<<< HEAD:charts/gaps/1.6.4/Chart.yaml
    version: 1.6.7
=======
    version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/gaps/2.0.0/Chart.yaml
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
