# Default values for Gaps.

image:
  repository: housewrecker/gaps
  pullPolicy: IfNotPresent
  tag: v0.8.8

strategy:
  type: Recreate

services:
  main:
    port:
      port: 8484

env: {}
  # TZ: UTC

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /usr/data




appVolumeMounts:
  data:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/data"
