# Default values for deluge.

image:
  repository: linuxserver/deluge
  pullPolicy: IfNotPresent
  tag: version-2.0.3-2201906121747ubuntu18.04.1

strategy:
  type: Recreate

service:
  main:
    port:
      port: 8112
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      name: bittorrent-tcp
      protocol: TCP
      targetPort: 51413
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      name: bittorrent-udp
      protocol: UDP
      targetPort: 51413

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
  downloads:
    enabled: false
    emptyDir: false
    setPermissions: true
    mountPath: "/downloads"
