apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: kms
version: 2.0.0
# upstream_version:
appVersion: "minimal"
description: Private Windows Activation Server for development and testing
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/kms
icon: https://github.com/KMS/KMS/blob/phantom-develop/Logo/512.png?raw=true
keywords:
  - kms
sources:
  - https://github.com/truecharts/charts/tree/master/charts/kms
  - https://github.com/SystemRage/py-kms
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 2.0.0
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Kjeld Schouten-Lebbing
    email: kjeld@schouten-lebbing.nl
    url: truecharts.org
# annotations:
