apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: unifi
<<<<<<< HEAD:charts/unifi/1.3.4/Chart.yaml
version: 1.3.4
=======
version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/unifi/2.0.0/Chart.yaml
upstream_version: 1.5.1
appVersion: "auto"
description: Ubiquiti Network's Unifi Controller
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/unifi
icon: https://dl.ubnt.com/press/logo-UniFi.png
keywords:
  - ubiquiti
  - unifi
sources:
  - https://github.com/truecharts/charts/tree/master/charts/unifi
  - https://github.com/jacobalberty/unifi-docker
  - https://unifi-network.ui.com
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
<<<<<<< HEAD:charts/unifi/1.3.4/Chart.yaml
    version: 1.6.7
=======
    version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/unifi/2.0.0/Chart.yaml
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: whiskerz007
    email: whiskerz007@users.noreply.github.com
    # url:
# annotations:
