# Default values for Unifi.

image:
  repository: jacobalberty/unifi
  tag: 6.0.45
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

startAsRoot: true

envTpl:
# Permissions Settings
  UNIFI_GID: "{{ .Values.PUID }}"
  UNIFI_UID: "{{ .Values.PGID }}"

services:
  main:
    port:
      port: 8443
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 8080
      protocol: TCP
      targetPort: 8080
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 3478
      protocol: UDP
      targetPort: 3478

env: {}
  # TZ:
  # PUID:
  # PGID:

persistence:
  config:
    enabled: false
    emptyDir: false




appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/unifi"
