apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: ombi
version: 2.0.0
upstream_version: 8.0.1
appVersion: "auto"
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/ombi
icon: https://img3.androidappsapk.co/wiLDnuwrCWctiiW62ALcj4eIpNbzeRH_UNPo7eqlpYvGkCQYSTybaI4xVRLKGjnlamlV=s300
keywords:
  - ombi
  - plex
  - emby
  - sonarr
  - radarr
  - couchpotato
sources:
  - https://github.com/truecharts/apps/tree/master/stable/ombi
  - https://github.com/k8s-at-home/charts/tree/master/charts/ombi
  - https://github.com/tidusjar/Ombi
  - https://hub.docker.com/r/linuxserver/ombi
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
  - name: Ornias1993
    email: kjeld@schouten-lebbing.nl
    url: truecharts.org
# annotations:
