apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: freshrss
version: 2.0.0
upstream_version: 2.3.1
appVersion: "auto"
description: FreshRSS is a self-hosted RSS feed aggregator
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/freshrss
icon: https://github.com/FreshRSS/FreshRSS/blob/master/docs/img/FreshRSS-logo.png?raw=true
keywords:
  - freshrss
  - rss
sources:
  - https://github.com/truecharts/apps/tree/master/stable/freshrss
  - https://github.com/k8s-at-home/charts/tree/master/charts/freshrss
  - https://github.com/FreshRSS/FreshRSS
  - https://hub.docker.com/r/linuxserver/freshrss
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
