
# Default values for Ombi.

image:
  repository: ghcr.io/truecharts/ombi
  pullPolicy: IfNotPresent
  tag: v4.0.1222

strategy:
  type: Recreate

services:
  main:
    port:
      port: 3579

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

# Enabled mariadb
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: ombi
    username: ombi
    password: ombi
  primary:
    persistence:
      enabled: false

## TrueCharts Config


appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
