apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: grocy
version: 2.0.0
upstream_version: 4.3.1
appVersion: "auto"
description: ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/stable/grocy
icon: https://github.com/grocy/grocy/raw/master/public/img/appicons/mstile-150x150.png
keywords:
  - grocy
sources:
  - https://github.com/truecharts/apps/tree/master/stable/grocy
  - https://github.com/k8s-at-home/charts/tree/master/charts/grocy
  - https://github.com/grocy/grocy
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
    # condition:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
