##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: quentinsf/image-amd64-rollease2mqtt
  pullPolicy: IfNotPresent
  tag: latest

env: {}
  device: /dev/ttyACM0


##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
