apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: navidrome
<<<<<<< HEAD:charts/navidrome/1.6.4/Chart.yaml
version: 1.6.4
=======
version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/navidrome/2.0.0/Chart.yaml
upstream_version: 2.3.1
appVersion: "auto"
description: Navidrome is an open source web-based music collection server and streamer
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/navidrome
icon: https://github.com/deluan/navidrome/blob/master/ui/src/icons/android-icon-72x72.png?raw=true
keywords:
  - navidrome
  - music
  - streaming
sources:
  - https://github.com/truecharts/charts/tree/master/charts/navidrome
  - https://github.com/k8s-at-home/charts/tree/master/charts/navidrome
  - https://github.com/deluan/navidrome
  - https://hub.docker.com/r/deluan/navidrome
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
<<<<<<< HEAD:charts/navidrome/1.6.4/Chart.yaml
    version: 1.6.7
=======
    version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/navidrome/2.0.0/Chart.yaml
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
