# Default values for grocy.

image:
  repository: linuxserver/heimdall
  tag: version-2.2.2
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

services:
  main:
    port:
      port: 80

env: {}
  # TZ:
  # PUID:
  # PGID:

probes:
  startup:
    enabled: true

persistence:
  config:
    enabled: false
    emptyDir: false

## TrueCharts Config

appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
