apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: deluge
version: 2.0.0
upstream_version: 2.0.3
appVersion: "auto"
description: Deluge is a torrent download client
type: application
deprecated: false
home: https://github.com/grover31/apps/tree/staging/stable/deluge
icon: https://avatars2.githubusercontent.com/u/6733935?v=3&s=200
keywords:
  - deluge
sources:
  - https://github.com/cdr/code-server
  - https://github.com/k8s-at-home/charts/tree/master/charts/deluge
  - https://hub.docker.com/r/linuxserver/deluge/
  - https://deluge-torrent.org/
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 2.0.0
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: Grover131
# annotations:
