apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: qbittorrent
<<<<<<< HEAD:charts/qbittorrent/1.6.4/Chart.yaml
version: 1.6.4
=======
version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/qbittorrent/2.0.0/Chart.yaml
upstream_version: 7.2.1
appVersion: 4.3.0
description: qBittorrent is a cross-platform free and open-source BitTorrent client
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
keywords:
  - qbittorrent
  - torrrent
sources:
  - https://github.com/truecharts/charts/tree/master/charts/qbittorrent
  - https://github.com/k8s-at-home/charts/tree/master/charts/qbittorrent
  - https://hub.docker.com/r/linuxserver/qbittorrent/
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
<<<<<<< HEAD:charts/qbittorrent/1.6.4/Chart.yaml
    version: 1.6.7
=======
    version: 2.0.0
>>>>>>> [Common] Refactor Services (#212):charts/qbittorrent/2.0.0/Chart.yaml
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
