apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: node-red
version: 2.0.0
upstream_version: 5.2.1
appVersion: "auto"
description: Node-RED is low-code programming for event-driven applications
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/node-red
icon: https://nodered.org/about/resources/media/node-red-icon-2.png
keywords:
  - node-red
  - nodered
sources:
  - https://github.com/truecharts/charts/tree/master/charts/node-red
  - https://github.com/k8s-at-home/charts/tree/master/charts/node-red
  - https://github.com/node-red/node-red-docker
dependencies:
  - name: common
    repository: https://charts.truecharts.org/
    version: 2.0.0
    # condition:
    # tags:
    # import-values:
    # alias:
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: truecharts.org
# annotations:
