apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: mariadb
version: 2.0.0
appVersion: "auto"
description: MariaDB App for TrueNAS SCALE
type: application
deprecated: false
home: https://github.com/grover31/apps/tree/staging/stable/mariadb
icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - dtabase
  - sql
sources:
  - https://github.com/cdr/code-server
dependencies:
  - name: common
    repository: https://truecharts.org/
    version: 2.0.0
maintainers:
  - name: Grover131
# annotations:
