# Default values for mariadb.

image:
  repository: bitnami/mariadb
  pullPolicy: IfNotPresent
  tag: 10.5.9-debian-10-r28

strategy:
  type: Recreate

#startAsRoot: true

service:
  main:
    port:
      port: 3306

appVolumeMounts:
  data:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/bitnami/mariadb"


# All values here are set as the docker defaults.
envTpl:
  MARIADB_ROOT_PASSWORD: "{{ .Values.mariadbrootpassword }}"
